---
- name: Deploy Flask App
  hosts: tags_ROLE_app server
  become: yes
  vars:
    app_name: flaskapp
    deploy_dir: /opt/flaskapp
    venv_dir: /opt/flaskapp/venv
    s3_bucket: obiora101
    artifact: "{{ app_name }}.tar.gz"
  roles:
    - role: flask_app
      vars:
        deploy_dir: "{{ deploy_dir }}"
        venv_dir: "{{ venv_dir }}"
        s3_bucket: "{{ s3_bucket }}"
        artifact: "{{ artifact }}"
